version: "3.1"
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_USER: foobar
      DB_PASSWORD: foobar
      DB_NAME: foobar
      DB_HOST: db
      DB_PORT: 5432
    ports:
    - "8000:8000"

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: foobar
      POSTGRES_USER: foobar
      POSTGRES_DB: foobar
    ports:
    - "5432:5432"
  flyway:
    image: flyway/flyway
    command: -connectRetries=60 migrate
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./sql:/flyway/sql
    environment:
      - FLYWAY_LOCATIONS=filesystem:sql
    depends_on:
      - db
